version: "3.9"
services:
  web:
    image: php-apache-mysql:8.0-xdebug3.0
    container_name: servidor-web-ET
    ports:
      - 80:80
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    volumes:
      - C:\Users\Usuario\PhpstormProjects\EstudioDeTatuajes\src\main\resources\templates:/var/www/html
    depends_on:
      - mysql-ET
    networks:
      - default

  mysql-ET:
    image: mysql:8.0.17
    container_name: mysql-ET
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ET
    ports:
      - "3306:3306"
    networks:
      - default
networks:
  default: